name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports: ['27017:27017']

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Waiting for MongoDB to start
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
            echo "MongoDB started"

      - name: Seed MongoDB
        working-directory: ./backend
        run: |
          npm install
          node ./seedTasksData.js

  test:
    runs-on: ubuntu-latest
    needs: mongo-init

    env:
      PORT: ${ { secrets.PORT } }
      MONGO_URI: ${ { secrets.MONGO_URI } }

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install BE Dependencies
        working-directory: ./backend
        run : npm install

      - name: Run BE Tests
        working-directory: ./backend
        run: npm test
